-- 001_create_schema.sql
-- Initial schema for mycrm (MySQL)

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS companies (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  inn VARCHAR(64) DEFAULT NULL,
  address VARCHAR(512) DEFAULT NULL,
  contact_phone VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED DEFAULT NULL,
  role ENUM('admin','manager','driver','client') NOT NULL DEFAULT 'client',
  first_name VARCHAR(128) DEFAULT NULL,
  last_name VARCHAR(128) DEFAULT NULL,
  phone VARCHAR(64) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  password_hash VARCHAR(255) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (company_id),
  INDEX (role),
  INDEX (phone),
  INDEX (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS drivers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  license_number VARCHAR(64) DEFAULT NULL,
  license_category VARCHAR(16) DEFAULT NULL,
  license_expiry DATE DEFAULT NULL,
  insurance VARCHAR(255) DEFAULT NULL,
  med_examination DATE DEFAULT NULL,
  rating_avg DECIMAL(3,2) DEFAULT 0,
  status ENUM('free','on_trip','off','vacation','repair') DEFAULT 'free',
  location_lat DECIMAL(10,7) DEFAULT NULL,
  location_lng DECIMAL(10,7) DEFAULT NULL,
  photo VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (user_id),
  INDEX (status),
  INDEX (rating_avg)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED DEFAULT NULL,
  driver_id BIGINT UNSIGNED DEFAULT NULL,
  make VARCHAR(128) DEFAULT NULL,
  model VARCHAR(128) DEFAULT NULL,
  class VARCHAR(64) DEFAULT NULL,
  plate_number VARCHAR(32) DEFAULT NULL,
  year SMALLINT DEFAULT NULL,
  seats SMALLINT DEFAULT NULL,
  capacity DECIMAL(10,2) DEFAULT NULL,
  status ENUM('ok','repair','written_off','accident') DEFAULT 'ok',
  photos JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (company_id),
  INDEX (driver_id),
  INDEX (plate_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  external_number VARCHAR(128) DEFAULT NULL,
  status ENUM('draft','new','accepted','in_transit','delivered','completed','canceled','canceled_with_penalty') DEFAULT 'new',
  client_id BIGINT UNSIGNED DEFAULT NULL,
  company_id BIGINT UNSIGNED DEFAULT NULL,
  assigned_driver_id BIGINT UNSIGNED DEFAULT NULL,
  assigned_vehicle_id BIGINT UNSIGNED DEFAULT NULL,
  type_service VARCHAR(128) DEFAULT NULL,
  tariff_type VARCHAR(128) DEFAULT NULL,
  price DECIMAL(12,2) DEFAULT 0,
  price_client DECIMAL(12,2) DEFAULT 0,
  price_driver DECIMAL(12,2) DEFAULT 0,
  payment_status ENUM('pending','paid','failed') DEFAULT 'pending',
  passengers_count INT DEFAULT 0,
  notes TEXT DEFAULT NULL,
  manager_comment TEXT DEFAULT NULL,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  scheduled_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (status),
  INDEX (assigned_driver_id),
  INDEX (created_at),
  INDEX (client_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_points (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  seq SMALLINT NOT NULL DEFAULT 0,
  city VARCHAR(128) DEFAULT NULL,
  address VARCHAR(512) DEFAULT NULL,
  lat DECIMAL(10,7) DEFAULT NULL,
  lng DECIMAL(10,7) DEFAULT NULL,
  arrival_time_estimated DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX (order_id),
  INDEX (seq)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_passengers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(64) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_files (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  filename VARCHAR(255) NOT NULL,
  path VARCHAR(1024) NOT NULL,
  uploaded_by BIGINT UNSIGNED DEFAULT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tracking (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  driver_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED DEFAULT NULL,
  lat DECIMAL(10,7) DEFAULT NULL,
  lng DECIMAL(10,7) DEFAULT NULL,
  speed DECIMAL(6,2) DEFAULT NULL,
  recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (driver_id),
  INDEX (order_id),
  INDEX (recorded_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ratings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  rater_user_id BIGINT UNSIGNED DEFAULT NULL,
  driver_id BIGINT UNSIGNED DEFAULT NULL,
  rating TINYINT UNSIGNED DEFAULT 0,
  comment TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (order_id),
  INDEX (driver_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED DEFAULT NULL,
  entity_type VARCHAR(64) DEFAULT NULL,
  entity_id BIGINT UNSIGNED DEFAULT NULL,
  action VARCHAR(128) DEFAULT NULL,
  payload JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (user_id),
  INDEX (entity_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Foreign keys (best-effort, some fields optional)
ALTER TABLE users
  ADD CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE drivers
  ADD CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE vehicles
  ADD CONSTRAINT fk_vehicles_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_vehicles_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE orders
  ADD CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_orders_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_orders_driver FOREIGN KEY (assigned_driver_id) REFERENCES drivers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_orders_vehicle FOREIGN KEY (assigned_vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE order_points
  ADD CONSTRAINT fk_orderpoints_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE order_passengers
  ADD CONSTRAINT fk_passengers_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE order_files
  ADD CONSTRAINT fk_files_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tracking
  ADD CONSTRAINT fk_tracking_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT fk_tracking_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE ratings
  ADD CONSTRAINT fk_ratings_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT fk_ratings_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE logs
  ADD CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;
